### ISSUE TITLE
Swift requirement of specifying names for subsequent method arguments? 

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#11]
By subsequent, I'm referring to anything after the first argument in a method's signature. 

Per the _Learn the Essentials of Swift_ playground:

> When you call a method, you pass in the first argument value without writing its name, **and every subsequent value with its name**. For example, this method on `Array` takes two parameters, and you only pass in the name for the second one:

```
var array = ["apple", "banana", "dragonfruit"]
array.insert("cherry", atIndex: 2)
```

The purpose of this doesn't seem to be syntactic sugar (making the code more readable), as specifying the first argument's name produces not just a warning, an error: `Extraneous argument label`. Is the purpose to help the compiler with overloaded functions or are there other reasons?

**Comment by tabinks** [comment]
The reason was to provide better compatibility with objective-c and Cocoa APIs.  The standard way of naming methods in objective-c was to put the type as the final component of the method name.  For example:

``` Objc
[myString stringFromFloat:x withPrefixString:y];
```

In this example, `x` would have been a Float, `y` a `String`  To make the naming more familiar in Swift they opted to drop the first parameter for naming consistency and to make it more familiar to objective-c developers.

``` swift
myString.stringFromFloat(x, withPrefixString:y);
```

### This is one of the changes in Swift 3.  The first parameter will be required to be named.
