### ISSUE TITLE
HW2 Instruction Question

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#17]
I have a question about the following instruction in HW2:

```
  "Declare a property in your ViewController to hold the Array."
```

What exactly does this mean?  Any resources someone could point me to that explains this concept?

Thanks

**Comment by adlee-dev** [comment]
I'm assuming he means the ViewController class needs a variable to hold the array made in the viewDidLoad() method (otherwise, the array would be local to viewDidLoad() and then be inaccessible after the function ends). See also: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Properties.html#//apple_ref/doc/uid/TP40014097-CH14-ID254

**Comment by tjp36** [comment]
Ah I get it now, thanks!
