### ISSUE TITLE
Assignment 1 Repository Link

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#2]
## Assignment 1
- Fill out [student information form]()
- Download and install Xcode and iOS SDK from Mac App Store
- Register as an Apple Developer (free or paid)
- Watch this video: [2016: Getting Started with Swift](https://developer.apple.com/videos/play/wwdc2016/404/)
- From the Apple Developer site, complete the [Start Developing iOS Apps (Swift)](https://developer.apple.com/library/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/index.html) tutorial through "Connect the UI to Code" (_Do not complete "Work with View Controllers"_)
  - Withing the tutorial there is a [Learn the Essentials of Swift](https://developer.apple.com/sample-code/swift/downloads/Start-Dev-iOS-Apps-01.zip) Playground.  Please download this and follow through the written tutorial.  Include with file in your final git repository that you submit.  There should be noticeable work in this Playground.
- Post a message to the course forum in the "Welcome to iOS Development" thread.
## Submit in GitHub repository

GitHub Classroom Link: https://classroom.github.com/assignment-invitations/5f36de047b1f610c9e36a235d02a9664
- The application you created in the tutorial
- The Playground you worked through

Assignment 1 is due Monday, June 27, 2016 at 5:29pm.

**Comment by tabinks** [comment]
To clarify: 
Do **NOT** complete the the "Work with View Controllers".

**Comment by kbsrunschi** [comment]
For running the app in simulator, I am not able to click in the text box to bring up the keyboard. It appears to be because my storyboard is locked due to being in the git repo. Is this normal? Should we be able to click in the text box and type/bring up the keyboard even when it says "locked"... should it even be locked? (This is for Building the UI part of the hw)

Thanks!

**Comment by tabinks** [comment]
I'm not sure what you mean by "locked", but yes, tapping on the text box should bring the keyboard up.  Being in the git repo shouldn't make a difference.  This is not normal.

**Comment by kbsrunschi** [comment]
Hm, yea no matter where I put the folder of code, it says I am locked because the code is in a remote repository. I haven't gone all the way through setting up a developer account (because it keeps asking me to pay $99, no option for free) so maybe because of that?  (See top right corner)

![image](https://cloud.githubusercontent.com/assets/14914274/16251512/3cb37d7c-37ec-11e6-9ab4-d42b6e4c5c07.png)

**Comment by tabinks** [comment]
@kbsrunschi Can you move this to a new issue?
