### ISSUE TITLE
Class initializing

### ISSUE THREAD

**Issue by pikashoes** [uchicago-mobi/2016-Summer-Forum#23]
I've just started the homework, and I created a class. I get an error saying that the class Animal has no initializers.

I'm following this tutorial from the class page (https://www.raywenderlich.com/115279/swift-2-tutorial-part-2-a-simple-ios-app) very closely, and don't really see a difference in the way I wrote the code. Also, I'm not sure if this is a basic question, but how do you declare the type UIImage?

**Comment by susanstevens** [comment]
Good questions! In Swift, non-optional properties must be given values when the class is initialized, because they can never be nil.  So if I have a class that looks like this:

class MyClass {
    var count: Int
}

I need to include an initializer like this:

init(count: Int) {
    self.count = count
}

Declaring and initializing a UIImage looks like this:

let myImage: UIImage = UIImage(named: "cat")

**Comment by pikashoes** [comment]
That worked! Thank you.
