### ISSUE TITLE
Can we keep issues open until the homework closes?

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#24]
Just a housekeeping request - issues that other students open for questions are being closed before the homework is due which makes it hard to catch up on other peoples threads --> As students ask questions, can we keep them open (even if the student resolved their question) until 530 on Monday? 

Thank you!

**Comment by susanstevens** [comment]
It's helpful for Andrew and me if issues are closed once they're resolved.  That way we know which questions are still outstanding.  I'd recommend getting in the habit of checking closed issues when you have a question, just to see if it's already been answered.  You can also configure email notifications so that you see all of the questions and responses as they are posted.

**Comment by kbsrunschi** [comment]
Ok - there are also labels available -- can we tag things for each homework so we can personal show all issues and filter by homework?

**Comment by susanstevens** [comment]
That sounds like a good idea to me.

**Comment by tabinks** [comment]
I like that idea too.  I added a `homework` label.

**Comment by kbsrunschi** [comment]
Thank you! :)
