### ISSUE TITLE
What Exactly Needs to be in our Table View Cells?

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#64]
Looking at the example pictures for the assignment, it looks like each table view cell has 2 components:  A title (in larger font) and the text (in smaller font).  The text is obviously from the "Text" field.  But where is the title (larger font) coming from in the JSON?

<img width="768" alt="2-app" src="https://cloud.githubusercontent.com/assets/6525670/17219151/f1cdc318-54af-11e6-8673-eebaad79221e.png">

**Comment by benvcarr** [comment]
On a related note - the API we're given doesn't actually return search _results_. It returns links to other DuckDuckGo queries. Is this intended? It won't match that image at all in that case.

Likewise, the Description returned by DDG has weird text spacing issues with the keywords that look pretty ugly. Is this okay? Examples:

`"Text" : "AppleA deciduous tree in the rose family best known for its sweet, pomaceous fruit, the apple."
"Text" : "Apple Inc.Apple Inc. is an American multinational technology company headquartered in Cupertino, California..."`

**Comment by tabinks** [comment]
In the text cell, you should show what is returned by the `Text` key and the url returned in the `FirstURL` field.  To get the autoresizing correct, I would allows the `Text` to be the view that resizes and keep the `FirstURL` constant.

You should use the `FirstURL` URL to show in detail view controller.  The detail view controller should look something like this:

![ddg](https://cloud.githubusercontent.com/assets/93689/17221118/02d7e384-54b8-11e6-898d-166bdf4967bb.png)

As far as the formatting the text, you can leave it as is, you are not required to reformat it.  If you want to make it look better, though, you can try to clean it up with a little Swift string processing. From the looks of it, the easiest way to use this would be to use `Result` (instead of `Text`) and split the string on the `<\a>`.

``` swift
// The result from DDG
let result = "<a href=\"https://duckduckgo.com/Apple\">Apple</a>A deciduous tree in the rose family best known for its sweet, pomaceous fruit, the apple."

// Use componentsSeparatedByString to split the string.
let text = result.componentsSeparatedByString("</a>")
print(text[1])
```

**Comment by tjp36** [comment]
Ok so we only need to show one thing in each table view cell:  the "Text"?  and when we tap on a cell it should open the FirstURL?

**Comment by tabinks** [comment]
You should show the text and the url.

**Comment by tabinks** [comment]
I have updated the description in the write-up to clarify this.  Thanks.

**Comment by tjp36** [comment]
Thanks!
