### ISSUE TITLE
Tableview array is going one past array lenght

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#71]
So Im having a new error (wasnt a problem until this morning) where the results are trying to be displayed in the master view controller table and the init load of results is fine, then when I do a new search, it gets the data and, lets say my search of "fitness" returns 7 results, it finds all 7 and parses them, but then goes one more to 8, causing my app to error out because its nil.

How do I prevent this/is this a compounding error of something else?

**Comment by susanstevens** [comment]
Are you returning 8 instead of 7 in `tableView(_:numberOfRowsInSection:)` for some reason?

**Comment by kbsrunschi** [comment]
im doing results.count but ill print out what they expect the array count to be

**Comment by kbsrunschi** [comment]
yea its finding 8 but when i print out the array, there are only 7

**Comment by susanstevens** [comment]
Take a closer look at what's being returned in the "Related Topics" array.  I'd recommend putting the search url into a web browser so that you can see the results.  You can download a Chrome extension like [this one](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa) that formats the JSON and makes it a lot easier to read.  

Does everything that's returned in the "Related Topics" array have the keys you're looking for, Result, FirstURL and Text?  If not, you'll need to filter out the objects in the array that you don't want.

**Comment by tabinks** [comment]
One thing to check is that `results` has any data at the time that the table is reloading.  Make sure that the table isn't being reloaded before the new results have come back.  You might have to set the number of rows to 0 until the new data is ready.

Something like:

``` swift
if results.count == nil  {
return 0
} else {
return results.count
}
```

**Comment by kbsrunschi** [comment]
Everything looks good and the results print out in my Shared Networking class, its only when it goes to put them into the cells. "Fitness" is a problem query but "computer science" has no issues.

**Comment by kbsrunschi** [comment]
Oh nvm I see, its pulling in extra info. Thanks!
