### ISSUE TITLE
app engine url not updating?

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#99]
Do we need to do something special to get the url to update? My local host is updating but not being reflected in the .appspot.com domain

**Comment by kbsrunschi** [comment]
Im also getting 'db is not defined' but you also dont define db in your python code...

**Comment by jbairUChicago** [comment]
Regarding the first change, it's worth a check to see if the subdomain has actually been added through a DNS propagation tool like https://www.whatsmydns.net/#A/stachesandglasses.appspot.com. 

If it has and you can't see it, besides waiting for TTL to expire, you could flush DNS or add one of those resolved IPs from the above link (with your subdomain) to your host file.

**Comment by jbairUChicago** [comment]
Disregard that. appspot.com DNS is configured to respond on any subdomain, regardless of whether a user has reserved it.

**Comment by jbairUChicago** [comment]
In my case, I followed the nodejs tutorial, but the underlying web framework shouldn't make a difference since they all have common configuration components (app.yaml) and use gcloud commands for management. 

The app id and the gcloud app deploy command were what finally put everything in place for me. 

I can't tell or recall exactly if having billing enabled is required (even for essentially free app engine instances). In my case, billing is enabled. 

The tutorial: https://cloud.google.com/nodejs/getting-started/hello-world

**Comment by tabinks** [comment]
It's usually nearly instantaneous from when you upload it.  Take a look at the console logs and it should tell you if there was a problem.

**Comment by tabinks** [comment]
> Im also getting 'db is not defined' but you also dont define db in your python code...

Can you be more specific about the error.  The datastore class is called `ndb`, could it just be a typo?

**Comment by kbsrunschi** [comment]
I forgot to run the update script DOH. Im good :)
